services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_MIDTRANS_CLIENT_KEY: ${NEXT_PUBLIC_MIDTRANS_CLIENT_KEY}
    restart: unless-stopped
    ports:
      - "3080:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    labels:
      - traefik.enable=true
      - traefik.docker.network=n8n_default
      - "traefik.http.routers.catetin.rule=Host(`catetin.co`)"
      - traefik.http.routers.catetin.entrypoints=web,websecure
      - traefik.http.routers.catetin.tls=true
      - traefik.http.routers.catetin.tls.certresolver=mytlschallenge
      - traefik.http.services.catetin.loadbalancer.server.port=3000
    networks:
      - n8n_default

networks:
  n8n_default:
    external: true
